### ISSUE TITLE
Flatpak: BeeRef fails to start. Throws a critical Qt error (cannot mix incompatible Qt libraries)

### ISSUE THREAD

**Issue by ajz3d** [rbreu/beeref#120]
**Describe the bug**
Flatpak build of BeeRef no longer starts. Instead, it throws a critical Qt error:

```
CRITICAL Qt: Cannot mix incompatible Qt library (6.7.1) with this library (6.7.2)
```

**System info**
Debian 12.5 (Bookworm).
GNOME 43.
BeeRef 0.3.3.

**To Reproduce**
``` sh
flatpak run org.beeref.BeeRef
```

```
INFO __main__: Starting BeeRef version 0.3.3
INFO __main__: Using settings: /home/***/.var/app/org.beeref.BeeRef/config/BeeRef/BeeRef.ini
INFO __main__: Logging to: /home/***/.var/app/org.beeref.BeeRef/config/BeeRef/BeeRef.log
CRITICAL Qt: Cannot mix incompatible Qt library (6.7.1) with this library (6.7.2)
```

**Comment by Deevad** [comment]
Hey, I also ran into the same problem. 

I reported it here: https://github.com/flathub/org.beeref.BeeRef/issues/65

**Comment by Deevad** [comment]
It is fixed thanks to [dginovker](https://github.com/dginovker)on the thread I mentioned before , just update your Flatpak.

**Comment by ajz3d** [comment]
That was lightning fast! Thanks for the fix, @dginovker. And @Deevad - thanks for letting me know.
I guess this bug report can now be closed.
