### ISSUE TITLE
Overview of recent projects

### ISSUE THREAD

**Issue by prokoudine** [rbreu/beeref#15]
It's great to have a clean canvas at startup, but sometimes it's also useful to be able to quickly locate a past project.

So how about an optional grid of previews for recently opened projects? Similar to this mockup for MuseScore 4:

https://musescore.org/sites/musescore.org/files/2020-06/Strategy_2020_V03.004.png

**Comment by andrsd** [comment]
I use **File | Open recent** for this. I am on a Mac, so I enabled menu bar via **View | Show Menu Bar**, so the app feels more Macy.

Just a feature you might find useful in the meanwhile.

**Comment by prokoudine** [comment]
I am well aware of this, thanks :)

**Comment by rbreu** [comment]
Oh yes, having recent files on the start screen is definitely on my todo list!

**Comment by rbreu** [comment]
List of recent files is now committed to the main branch, without thumbnails yet. I'm closing this issue for now, thumbnails will stay on my todo list.
