### ISSUE TITLE
Unable to build in virtual environment

### ISSUE THREAD

**Issue by andrsd** [rbreu/beeref#16]
**Describe the bug**

If building in a virtual environment, installing packages via `pip -r requirements/dev.txt` won't pull all needed packages.

**To Reproduce**
1. `python3 -m venv env`
2. `env/bin/activate`
3. `pip install requirements/dev.txt`

**Expected behavior**

Install all needed packages.

**Screenshots**

N/A

**Debug log:**

N/A

**Fix**
Doing:
- `pip install PyQt6` 
- `pip install exif`
- `pip install rectangle-packer`

Fixed the problem.

Here is also output from `pip freeze` from my virtual environment (IDK if that's will help you more):
[beeref-pip-freeze.txt](https://github.com/rbreu/beeref/files/6950705/beeref-pip-freeze.txt)

My environment is MacOSX, so packackages like `macholib` are platform specific (probably pulled in by `pyinstaller` - I am not a python guru).

**Comment by rbreu** [comment]
The dev.txt is only meant to contain further development tools. The dependencies of BeeRef itself are contained in setup.py. Run the following line from within your git clone:
```
pip install -e .
```
Please make sure you do this so you get the correct PyQt version. (The recent one has an annoying bug with modifier keys, though it might not affect MacOS.)

**Comment by andrsd** [comment]
Ok, doing `pip install -e .` pulled in the required stuff. I misread your note for devs, so I failed to do that step.

Thank you for you help :+1:
