### ISSUE TITLE
Context menu too short on first use

### ISSUE THREAD

**Issue by wayfu** [rbreu/beeref#25]
**Describe the bug**
The pop-open context menu submenus are shorter on their first open than on subsequent ones, cutting off the last item.

**To Reproduce**
1. Open BeeRef
2. Open the context menu
3. Navigate to a submenu
4. Observe
5. Navigate to a different submenu
6. Go back to the first one, it will now show all items fully

**Expected behavior**
I would expect menus to be the required size from the first use.

**Screenshots**
![image](https://user-images.githubusercontent.com/7761390/132252688-0dd21cc8-dcf9-4a9f-8586-74c4491e61fd.png)

**My System**
Win10

**Comment by rbreu** [comment]
Huh, weird. The white lines are also strange.

**Comment by rbreu** [comment]
I've upgraded from Qt 6.4 to Qt 6.6. This will go out in the next release. If the issue persists after that, feel free to re-open this issue.
