### ISSUE TITLE
Importing SVG from web does not work on Linux

### ISSUE THREAD

**Issue by myselfhimself** [rbreu/beeref#27]
Hello :) Thanks to BeeRef

Using the 0.2.0 Binary file, started from a .desktop shortcut

Go to https://github.com/rbreu/beeref/blob/v0.2.0/beeref/assets/logo.svg

Drag the logo image from Firefox to the BeeReef (always on top on) window

Observe the error dialog:
![image](https://user-images.githubusercontent.com/1265346/132429156-998a8844-2872-4371-90be-8c67169127cc.png)

Transcript of the error dialog image:
Problem loading images
1 image(s) out of 1 could not be opened:
https://raw.githubusercontent.com/rbreu/beeref/c308c08a07a6bce0ee1ece487f924811f1e56053/beeref/assets/logo.svg

:)

**Comment by rbreu** [comment]
Does this still happen? I could never reproduce it. Does the same happen when saving the svg and then inserting the svg via Insert -> Insert Images?

**Comment by rbreu** [comment]
Closing this issue. If it still happens, feel free to re-open or report a new issue.
