### ISSUE TITLE
Are viruses welcome? Or...

### ISSUE THREAD

**Issue by LLKoder** [rbreu/beeref#41]
I checked this app at viruses at [VirusTotal](https://www.virustotal.com) and result was strange for open sources app.

BeeRef-0.2.0-linux - [1 security vendor flagged this file as malicious](https://www.virustotal.com/gui/file/8e98dfd3b9783649805e067238b3f4df00c1da24b012b952e44757510cf241d2)
BeeRef-0.2.0-windows.exe - [6 security vendors flagged this file as malicious](https://www.virustotal.com/gui/file/727f75f65910abed452c4207832d2ec2f5d6d418678bddbed524f76631d20fb0)
Source code (tar.gz) - [No security vendors flagged this file as malicious](https://www.virustotal.com/gui/file/3bd01e30ece5c845f6c39b452b608f6448540283ab81f0b05db8db1c4bf17fe0)

Any ideas are welcome...

**Comment by mojamuto** [comment]
![imagen](https://user-images.githubusercontent.com/36079583/147092393-46087475-b541-4bae-94e1-834f0ba0dfe1.png)
 BeeRef-0.2.0-linux is 0

**Comment by LLKoder** [comment]
When I tested app virus was there. But it's good news.
Windows version has 5 suspicious files. :(

**Comment by mojamuto** [comment]
In general all antivirus have false positives and .exe files tend to have more than others.
In another project they talk about them:
https://github.com/t3knomanzer/maxmix-software/issues/213

**Comment by codl** [comment]
In particular, the windows build of beeref is built with pyinstaller, which is known to produce false positives in some antivirus software, see [pyinstaller's issue tracker](https://github.com/pyinstaller/pyinstaller/issues?q=is%3Aissue+label%3Aantivirus-false-positives)

**Comment by Hunanbean-Collective** [comment]
Considering the amount of "false positives" (i just checked latest version) perhaps make a Portable Version that does not require Installation., I mean, since it is being claimed it is the installer causing the positives. Best wishes
