### ISSUE TITLE
FR: Transparency and BW modes

### ISSUE THREAD

**Issue by gerroon** [rbreu/beeref#42]
Hi,

It would be very helpful if the image transparency can be modified in the canvas. Also being able to convert color images to BW temproarily is very helpful.

Thanks for making this app.

**Comment by cogwheeloftime** [comment]
Being able to bind a key to toggle grayscale would be great. Been wanting to do that within BeeRef for awhile.

**Comment by rbreu** [comment]
This is now implemented and will go out with the next release.
