### ISSUE TITLE
Open a file saved by a previous version 

### ISSUE THREAD

**Issue by Hattiffnat** [rbreu/beeref#47]
When trying to open a file saved by a previous version:

> CRITICAL __main__: Unhandled exception
> Traceback (most recent call last):
>   File "beeref/fileio/__init__.py", line 100, in run
>   File "beeref/fileio/__init__.py", line 43, in load_bee
>   File "beeref/fileio/sql.py", line 55, in wrapper
>   File "beeref/fileio/sql.py", line 207, in read
> TypeError: __init__() got an unexpected keyword argument 'crop'

**Comment by rbreu** [comment]
I can't reproduce this and I don't know between which versions you were switching.
