### ISSUE TITLE
Jagged edges when rotating image. No antialiasing?

### ISSUE THREAD

**Issue by Redstonerayy** [rbreu/beeref#61]
**Describe the bug**
When rotating an image, the edges are jagged which could be because no antialiasing is used.
I think this can be enabled by setting a window hint like [here](https://stackoverflow.com/questions/44233028/how-to-smoothing-jagged-edges-on-curved-lines-and-diagonals-on-pyqt4)

**To Reproduce**
1. Open a bee file and rotate an image

**Expected behavior**
It should rotate and look good.

**Comment by fislysandi** [comment]
ye i think this project is abandoned but it can be revived by someone

maybe we need some attention to this project since pureref hasnt been updated in a while.

**Comment by fislysandi** [comment]
unless a new maintainer comes to this project dont excpect for this to be fixed.

**Comment by Redstonerayy** [comment]
ok, thanks for the info

**Comment by Symbian9** [comment]
@mini-ninja-64 May you take a look on implementing antialiasing for *BeeRef* app? (in your fork)

In [*PureRef*](https://alternativeto.net/software/pureref/about/) app it was implemented as Bilinear Sampling, applied to each image frame by default (and there is option to turn it off via context menu *"Images > Selection > Toggle Bilinear Sampling"* or with <kbd>Alt</kbd>+<kbd>T</kbd> shortcut).

**Comment by mini-ninja-64** [comment]
Seems fairly simple to add and great QoL improvement, just hard coding the flag acheives a much prettier result as shown in the attached image:

![before_after](https://user-images.githubusercontent.com/15253132/221998245-0b914a18-5c44-4331-8030-13d7d91d43ea.png)

I can raise an issue on my fork and implement when I have some time

**Comment by Symbian9** [comment]
> just hard coding the flag acheives a much prettier result as shown in the attached image:

@mini-ninja-64 It looking good!

But I mean not only _"frame edge"_ antialiasing, but also _"bilinear sampling applying on all images"_ after each change on canvas (zooming, moving, image frame resizing, etc.)

Try to use some blueprint as reference images.

![Screenshot_2023-03-01_16-44-28](https://user-images.githubusercontent.com/13188580/222174849-891e45c1-5454-4674-aec2-ae09664cb1fa.png)

**Comment by Symbian9** [comment]
> Seems fairly simple to add and great QoL improvement, just hard coding the flag acheives a much prettier result as shown in the attached image:
> 
> ![before_after](https://user-images.githubusercontent.com/15253132/221998245-0b914a18-5c44-4331-8030-13d7d91d43ea.png)
> 
> I can raise an issue on my fork and implement when I have some time

And I just found that there is already open pull request that adds both: frame edge antialising and image filters during scaling/moving

- https://github.com/rbreu/beeref/pull/60#issue-1206103054
