### ISSUE TITLE
BeeRef Crashes when I change to other window using the drawing tablet

### ISSUE THREAD

**Issue by gelatinbomb** [rbreu/beeref#67]
**Describe the bug**
Sadly I haven't managed to replicate exactly the bug pattern but essentially is when I have multiple pics on BeeRef, I do something on Beeref it could be moving the canvas or moving some pic. Then I came back to Krita. Beeref crashes on the moment I do that. I find it happens mostly when I have the "on top" feature activated. 
I use an XP-Pen Tablet so maybe that have something to do with the problem.

**To Reproduce**
1. Open beeref with multiple pictures
2. Do something with the pictures on Beeref while the "on top picture" is on.
3. Go back to the other program you are using

**Expected behavior**
I expect the software to do nothing when I change to the other program.

I think I mess up the debug log so I will upload it when I manage to crash beeref again. If I find any extra detail I will post it.

**Comment by rbreu** [comment]
Did you ever get the debug log? Does the issue still happen?

**Comment by gelatinbomb** [comment]
> Did you ever get the debug log? Does the issue still happen?

I haven't managed to replicate it with the new release. So maybe it's fixed. Something you have to keep in mind is that "on top" feature included in beeref does not work in kde. I'm using the kde "on top" feature.

**Comment by gelatinbomb** [comment]
> Did you ever get the debug log? Does the issue still happen?

I haven't managed to replicate it with the new release. So maybe it's fixed. Something you have to keep in mind is that "on top" feature included in beeref does not work in kde. I'm using the kde "on top" feature.

**Comment by rbreu** [comment]
Yeah, window managers can choose to ignore the "On top" option. I can't influence that behaviour.
