### ISSUE TITLE
Feature Suggestion: Unversioned executable name

### ISSUE THREAD

**Issue by hced** [rbreu/beeref#73]
**Suggestion: Clean executable name without version**
For easier OS management, I prefer executable names that are generic.

Example where versioned names become cumbersome:

In Windows there is a Start menu folder where you can manually put links to programs. Since BeefRef is a portable app (aside: where does it save its preferences?) I have to put a link to BeeRef in this folder in order to be able to run it via Windows Start Menu. Issue: For every new version, I'll have to redo the link.n (Manually renaming the executable doesn't feel right, imo.)

**Comment by rbreu** [comment]
You can just rename the executable to whatever you want.

**Comment by goyalyashpal** [comment]
* with this being merged now
https://github.com/ScoopInstaller/Extras/pull/13124

you can you scoop package manager to install and use beeref effortlessly 😃
