### ISSUE TITLE
Unable to launch with failure to initialize QT platform plugin error on Linux Mint 21.2.

### ISSUE THREAD

**Issue by cogwheeloftime** [rbreu/beeref#86]
**Describe the bug**
Trying to launch the linux-ub22 app image results in failure. Nothing happens if launched through the desktop and trying to launch through the terminal prints an error. I've tried multiple solutions to get around what is described in the error log to see if something was wrong with my system but to no success.

**To Reproduce**

1. If nothing is wrong with my system, launching the app image by normal means on Ubuntu 22.04 (or a distro based on it in my case) results in failure.

**Expected behavior**
The app launches as normal like the previous version.

**Debug log:**

DEBUG Qt: Got keys from plugin meta data QList("vnc")
DEBUG Qt: looking at "/tmp/_MEIwRhmGi/PyQt6/Qt6/plugins/platforms/libqminimalegl.so"
DEBUG Qt: Found metadata in lib /tmp/_MEIwRhmGi/PyQt6/Qt6/plugins/platforms/libqminimalegl.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
    "MetaData": {
        "Keys": [
            "minimalegl"
        ]
    },
    "archlevel": 1,
    "className": "QMinimalEglIntegrationPlugin",
    "debug": false,
    "version": 394752
}

DEBUG Qt: Got keys from plugin meta data QList("minimalegl")
DEBUG Qt: checking directory path "_My home folder path to the appimage_/platforms" ...
DEBUG Qt: "/tmp/_MEIwRhmGi/PyQt6/Qt6/plugins/platforms/libqxcb.so" cannot load: Cannot load library /tmp/_MEIwRhmGi/PyQt6/Qt6/plugins/platforms/libqxcb.so: (libxcb-cursor.so.0: cannot open shared object file: No such file or directory)
DEBUG Qt: QLibraryPrivate::loadPlugin failed on "/tmp/_MEIwRhmGi/PyQt6/Qt6/plugins/platforms/libqxcb.so" : "Cannot load library /tmp/_MEIwRhmGi/PyQt6/Qt6/plugins/platforms/libqxcb.so: (libxcb-cursor.so.0: cannot open shared object file: No such file or directory)"
INFO Qt: Could not load the Qt platform plugin "xcb" in "" even though it was found.
CRITICAL Qt: This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: linuxfb, wayland-egl, offscreen, wayland, eglfs, minimal, vkkhrdisplay, xcb, vnc, minimalegl.

Aborted (core dumped)

**Comment by senntore** [comment]
See this https://github.com/rbreu/beeref/discussions/82#discussioncomment-7812086
You need to install `libxcb-cursor0` if you're using xorg. In wayland you would not have this issue.

**Comment by cogwheeloftime** [comment]
Thanks it worked. Sorry I failed to notice this issue was already resolved.

**Comment by senntore** [comment]
@cogwheeloftime No problem! It was solved in the discussion of release, so it was probably easy to miss it.
